2014/01/18 22:04:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "tester".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php
---
2014/01/18 22:04:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "tester".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php?r=cruge/ui/usermanagementadmin
---
2014/01/22 17:08:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "tester".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php?r=cruge/ui/usermanagementadmin
---
2014/01/22 17:32:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php?r=cruge/ui/usermanagementadmin
---
2014/02/01 00:28:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php
---
2014/02/01 00:31:47 [error] [application] UiController
CrugeUser->validate es false
<div class="errorSummary"><p>Por favor corrija los siguientes errores de ingreso:</p>
<ul>
<li>clave invalida</li>
</ul></div>
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/controllers/UiController.php (158)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 00:31:52 [error] [application] UiController
CrugeUser->validate es false
<div class="errorSummary"><p>Por favor corrija los siguientes errores de ingreso:</p>
<ul>
<li>clave invalida</li>
</ul></div>
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/controllers/UiController.php (158)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 00:32:02 [error] [application] UiController
CrugeUser->validate es false
<div class="errorSummary"><p>Por favor corrija los siguientes errores de ingreso:</p>
<ul>
<li>clave invalida</li>
</ul></div>
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/controllers/UiController.php (158)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 20:41:10 [error] [application] UiController
CrugeUser->validate es false
<div class="errorSummary"><p>Por favor corrija los siguientes errores de ingreso:</p>
<ul>
<li>clave invalida</li>
</ul></div>
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/controllers/UiController.php (158)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 20:41:15 [error] [application] UiController
CrugeUser->validate es false
<div class="errorSummary"><p>Por favor corrija los siguientes errores de ingreso:</p>
<ul>
<li>clave invalida</li>
</ul></div>
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/controllers/UiController.php (158)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 20:41:20 [error] [application] UiController
CrugeUser->validate es false
<div class="errorSummary"><p>Por favor corrija los siguientes errores de ingreso:</p>
<ul>
<li>clave invalida</li>
</ul></div>
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/controllers/UiController.php (158)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:01:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "gii"' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/dimaco/index.php?r=gii
---
2014/02/01 21:03:05 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.producto' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `producto`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:04:28 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.usuario' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `usuario`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:04:35 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.producto' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `producto`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:05:12 [error] [exception.CException] exception 'CException' with message 'La configuración del objeto debe ser un array conteniendo un elemento "class".' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/YiiBase.php:193
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CModule.php(386): YiiBase::createComponent(Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/gii/generators/model/ModelGenerator.php(17): CModule->getComponent('db1')
#2 [internal function]: ModelGenerator->actionGetTableNames('db1')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(Object(ModelGenerator), Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(ModelGenerator), Object(ReflectionMethod), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('getTableNames')
#9 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/getTa...')
#10 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#12 {main}
REQUEST_URI=/dimaco/index.php?r=gii/model/getTableNames&db=db1
HTTP_REFERER=http://localhost/dimaco/index.php?r=gii/model/index
---
2014/02/01 21:05:17 [error] [exception.CException] exception 'CException' with message 'La configuración del objeto debe ser un array conteniendo un elemento "class".' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/YiiBase.php:193
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CModule.php(386): YiiBase::createComponent(Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/gii/generators/model/ModelCode.php(428): CModule->getComponent('db1')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/validators/CInlineValidator.php(42): ModelCode->validateConnectionId('connectionId', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(ModelCode), 'connectionId')
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CModel.php(159): CValidator->validate(Object(ModelCode), NULL)
#5 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/gii/CCodeGenerator.php(159): CModel->validate()
#6 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('index')
#12 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#15 {main}
REQUEST_URI=/dimaco/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/dimaco/index.php?r=gii/model/index
---
2014/02/01 21:06:27 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.pedido' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `pedido`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:06:37 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.empresa' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `empresa`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:06:50 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.proveedor' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `proveedor`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:07:13 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.producto' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `producto`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:08:21 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dimaco.cruge_session' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `cruge_session`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/models/data/CrugeSession.php (90)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeFactory.php (46)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeUserManager.php (412)
2014/02/01 21:08:21 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "cruge_session" definida en la clase active record "CrugeSession" no se ha podido encontrar en la base de datos.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php:2362
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(CrugeSession))
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(1485): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/models/data/CrugeSession.php(90): CActiveRecord->findByPk('25')
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeFactory.php(46): CrugeSession::loadModel('25')
#5 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeUserManager.php(412): CrugeFactory->getICrugeSession('25')
#6 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(451): CrugeUserManager->loadSession('25')
#7 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(229): CrugeWebUser->getICrugeSession()
#8 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(242): CrugeWebUser->getId()
#9 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/auth/CWebUser.php(200): CrugeWebUser->getIsGuest()
#10 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(45): CWebUser->init()
#11 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CModule.php(387): CrugeWebUser->init()
#12 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(209): CModule->getComponent('user')
#13 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/auth/CAccessControlFilter.php(132): CWebApplication->getUser()
#14 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#15 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('producto')
#22 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#24 {main}
REQUEST_URI=/dimaco/index.php?r=producto
HTTP_REFERER=http://localhost/dimaco/index.php?r=gii/crud/index
---
2014/02/01 21:08:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dimaco.cruge_session' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `cruge_session`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/models/data/CrugeSession.php (90)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeFactory.php (46)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeUserManager.php (412)
2014/02/01 21:08:45 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "cruge_session" definida en la clase active record "CrugeSession" no se ha podido encontrar en la base de datos.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php:2362
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(CrugeSession))
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(1485): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/models/data/CrugeSession.php(90): CActiveRecord->findByPk('25')
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeFactory.php(46): CrugeSession::loadModel('25')
#5 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeUserManager.php(412): CrugeFactory->getICrugeSession('25')
#6 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(451): CrugeUserManager->loadSession('25')
#7 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(229): CrugeWebUser->getICrugeSession()
#8 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(242): CrugeWebUser->getId()
#9 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/auth/CWebUser.php(200): CrugeWebUser->getIsGuest()
#10 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(45): CWebUser->init()
#11 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CModule.php(387): CrugeWebUser->init()
#12 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(209): CModule->getComponent('user')
#13 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/auth/CAccessControlFilter.php(132): CWebApplication->getUser()
#14 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#15 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('producto')
#22 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#24 {main}
REQUEST_URI=/dimaco/index.php?r=producto
HTTP_REFERER=http://localhost/dimaco/index.php?r=gii/crud/index
---
2014/02/01 21:09:32 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dimaco.cruge_session' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `cruge_session`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/models/data/CrugeSession.php (90)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeFactory.php (46)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeUserManager.php (412)
2014/02/01 21:09:32 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "cruge_session" definida en la clase active record "CrugeSession" no se ha podido encontrar en la base de datos.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php:2362
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(CrugeSession))
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(1485): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/models/data/CrugeSession.php(90): CActiveRecord->findByPk('25')
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeFactory.php(46): CrugeSession::loadModel('25')
#5 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeUserManager.php(412): CrugeFactory->getICrugeSession('25')
#6 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(451): CrugeUserManager->loadSession('25')
#7 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(229): CrugeWebUser->getICrugeSession()
#8 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(242): CrugeWebUser->getId()
#9 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/auth/CWebUser.php(200): CrugeWebUser->getIsGuest()
#10 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/modules/cruge/components/CrugeWebUser.php(45): CWebUser->init()
#11 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CModule.php(387): CrugeWebUser->init()
#12 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(209): CModule->getComponent('user')
#13 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/auth/CAccessControlFilter.php(132): CWebApplication->getUser()
#14 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#15 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(291): CFilterChain->run()
#19 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('')
#21 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('producto')
#22 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#24 {main}
REQUEST_URI=/dimaco/index.php?r=producto
---
2014/02/01 21:10:09 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crugedemo.producto' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `producto`.
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/views/producto/index.php (20)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/controllers/ProductoController.php (128)
in /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php (14)
2014/02/01 21:10:09 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "producto" definida en la clase active record "Producto" no se ha podido encontrar en la base de datos.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php:2362
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Producto))
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/db/ar/CActiveRecord.php(1601): CActiveRecord->getTableSchema()
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/zii/widgets/CBaseListView.php(111): CDataProvider->getData()
#8 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/zii/widgets/CListView.php(211): CBaseListView->init()
#9 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(147): CListView->init()
#10 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/views/producto/index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#13 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#14 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/controllers/ProductoController.php(128): CController->render('index', Array)
#17 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/actions/CInlineAction.php(49): ProductoController->actionIndex()
#18 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#20 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#21 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#22 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#23 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#24 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(291): CFilterChain->run()
#25 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('')
#27 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('producto')
#28 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#29 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#30 {main}
REQUEST_URI=/dimaco/index.php?r=producto
---
2014/02/01 21:12:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php
---
2014/02/01 21:12:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
---
2014/02/01 21:12:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php
---
2014/02/01 21:12:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php?r=cruge/ui/usermanagementadmin
---
2014/02/01 21:18:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
HTTP_REFERER=http://localhost/dimaco/index.php?r=cruge/ui/rbacauthitemcreate&type=2&extra=
---
2014/02/01 21:18:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
---
2014/02/01 21:19:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "tester" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(270): CController->missingAction('tester')
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('tester')
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/tester')
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#5 {main}
REQUEST_URI=/dimaco/index.php?r=site/tester
---
2014/02/01 21:38:25 [error] [exception.CException] exception 'CException' with message 'El alias "zii.widgets.CGrigView" es inválido. Asegúrese de que apunta a un archivo PHP existente y que el archivo tiene permisos de lectura.' in /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/YiiBase.php:322
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWidgetFactory.php(146): YiiBase::import('zii.widgets.CGr...', true)
#1 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(146): CWidgetFactory->createWidget(Object(ProductoController), 'zii.widgets.CGr...', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(172): CBaseController->createWidget('zii.widgets.CGr...', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/views/producto/index.php(20): CBaseController->widget('zii.widgets.CGr...', Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#5 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#6 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/dimaco/protected/controllers/ProductoController.php(128): CController->render('index', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/actions/CInlineAction.php(49): ProductoController->actionIndex()
#10 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#13 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(291): CFilterChain->run()
#17 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(282): CController->run('index')
#19 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('producto/index')
#20 /Applications/XAMPP/xamppfiles/htdocs/dimaco/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#21 /Applications/XAMPP/xamppfiles/htdocs/dimaco/index.php(14): CApplication->run()
#22 {main}
REQUEST_URI=/dimaco/index.php?r=producto/index
---
